# Introduction to Numpy

In [1]:
import numpy as np


## Creating Arrays

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# creating a 0-D array with value 42
arr = np.array(42)
print(arr)

42


In [6]:
'''An array that has 1-D arrays as its elements is called a 2-D array.
Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:'''
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Dimensions of an Array

In [8]:
# number of dimensions of an array
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Numpy Array Indexing

In [11]:
#Accesing array elements
arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])

1
2


In [13]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

2nd element on 1st row:  2
5th element on 2nd row:  10


In [14]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [17]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


## Array Slicing

In [19]:
#Slicing arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])
print(arr[:4])
print(arr[-3:-1])

[5 6 7]
[1 2 3 4]
[5 6]


In [25]:
#Return every other element from index 1 to index 5:
print(arr[1:5:2])
#Return every other element from the entire array:
print(arr[::2])

[2 4]
[1 3 5 7]


In [26]:
#From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])


[7 8 9]


In [27]:
#From both elements, return index 2:
print(arr[0:2, 2])

[3 8]


In [28]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


## DataTypes in Numpy

In [30]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [31]:
#Create an array with data type string:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


## Type Conversion of Arrays

In [32]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


## Array Copy vs View

In [33]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [36]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
x[1] = 33
print(arr)
print(x)

[42 33  3  4  5]
[42 33  3  4  5]


## Array Shape

In [37]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


## Array Reshaping

In [39]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 2, 3)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [43]:
# if you do not have to specify an exact number for one of the dimensions in the reshape method pass -1 as the value, and NumPy will calculate this number for you.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [46]:
#converting a multidimensional array into a 1D array.
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


## Joining Arrays

In [47]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [48]:
arr1 = np.array([[1, 2], [3, 4]])


arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## Splitting Arrays

In [49]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [50]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


## Searching in Array

In [51]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [52]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)#To find the indexes where the value is even

print(x)

(array([1, 3, 5, 7], dtype=int64),)


## Sorting Arrays

In [54]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr)[::-1])

[3 2 1 0]


In [55]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [56]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [57]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## Random number in Numpy

In [58]:
from numpy import random

x = random.randint(100)#This will generate a random integer from 0 to 100

print(x)

47


In [59]:
x = random.rand()#This will generate a random float from 0 to 1

print(x)

0.5537824546801007


In [60]:
x=random.randint(100, size=(5))#This will generate 5 random integers from 0 to 100

print(x)

[83 84 21 79 58]


In [61]:
x = random.randint(100, size=(3, 5))#This will generate (3, 5) matrix of random integers from 0 to 100

print(x)

[[96 84 41 17 61]
 [14 37 67 64 27]
 [ 9 79 38 67 12]]


In [62]:
x = random.choice([3, 5, 7, 9])#This will randomly choose an integer from the array

print(x)

7
